dataloader:
  base_image_path: data/dataset/base_png
  train:
    n_images: 10
    save_path: data/dataset/train
    generate_input: True
    print_progress: True
  test:
    n_images: 20
    save_path: data/dataset/test
    generate_input: True
    print_progress: True
  
  batch_size: 4
  shuffle: True

optimizer: 
  lr: 0.001
  weight_decay: 0

epochs: 1

ckpt_path: 'unet_ckpt'
results_path: 'unet_results'
