dataloader:
  base_image_path: data/dataset/base_png
  train:
    n_images: 100
    save_path: data/dataset/train
    generate_input: True
    print_progress: True
  test:
    n_images: 20
    save_path: data/dataset/test
    generate_input: True
    print_progress: True
  
  batch_size: 1
  shuffle: True

optimizer: 
  lr: 0.001
  weight_decay: 0

epochs: 1

model_save_path: 'saved_models'

result_path: 'results'
